<img src="../../files/logo.png" width=200>

# Matrices

In [32]:
import numpy as np

In [7]:
matriz1 = np.mat('1 1 1 1; 2 2 2 2; 3 3 3 3 ; 4 4 4 4')

In [8]:
print(matriz1)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [9]:
matriz1.diagonal()

matrix([[1, 2, 3, 4]])

In [10]:
matriz1.reverse

AttributeError: 'matrix' object has no attribute 'reverse'

In [11]:
print(matriz1)
print(type(matriz1))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
<class 'numpy.matrix'>


In [14]:
matriz2 = np.mat('1 2 5 4; 2 5 1 0 ; 2 2 2 2; 2 3 8 1')

In [15]:
print(matriz1 + matriz2)

[[ 2  3  6  5]
 [ 4  7  3  2]
 [ 5  5  5  5]
 [ 6  7 12  5]]


In [16]:
print(matriz1 - matriz2)

[[ 0 -1 -4 -3]
 [ 0 -3  1  2]
 [ 1  1  1  1]
 [ 2  1 -4  3]]


In [19]:
matriz3 = np.mat('0; 0; 0; 0')
matriz3

matrix([[0],
        [0],
        [0],
        [0]])

In [20]:
multMat = matriz1 * matriz3
print(multMat)

[[0]
 [0]
 [0]
 [0]]


In [21]:
print(matriz1.cumsum())

[[ 1  2  3  4  6  8 10 12 15 18 21 24 28 32 36 40]]


In [22]:
print(matriz1.sum())

40


In [23]:
matriz1.size

16

In [33]:
matDatos = np.mat('5 2; 8 3')
matRes = np.mat('68; 104')

In [34]:
np.linalg.solve(matDatos,matRes)

matrix([[ 4.],
        [24.]])

<h2 style="color:#d62728">Ejercicio</h2>

Ana tiene el triple de edad que su hijo.  Dentro de 15 años, la edad de Ana será el doble de la de su hijo.
Cuántos años tiene Ana y su hijo?
a=3h

a+15=2(h+15)

In [1]:
import numpy as np

In [2]:
ecuaciones=np.mat('1 -3; 1 -2')
resultados=np.mat('0;15')

edades=ecuaciones.I*resultados
print('Ana tiene', edades[0],'años y su hijo tiene', edades[1])

Ana tiene [[45.]] años y su hijo tiene [[15.]]


2) Resuelve el siguiente sistema de ecuaciones 

- X + Y + Z = 6
- 2X - Y - Z = -3
- X -3Y +2Z = 5

In [24]:
import numpy as np

In [25]:
datos = np.mat("1 1 1; 2 -1 -1; 1 -3 2")
resultados = np.mat("6; -3; 5")
print(datos)

[[ 1  1  1]
 [ 2 -1 -1]
 [ 1 -3  2]]


In [26]:
print(resultados)

[[ 6]
 [-3]
 [ 5]]


In [27]:
print(resultados.transpose())

[[ 6 -3  5]]


In [28]:
inversa = datos.I
print(inversa)

[[ 3.33333333e-01  3.33333333e-01 -1.38777878e-17]
 [ 3.33333333e-01 -6.66666667e-02 -2.00000000e-01]
 [ 3.33333333e-01 -2.66666667e-01  2.00000000e-01]]


In [29]:
respuesta = inversa * resultados
print(respuesta)

[[1. ]
 [1.2]
 [3.8]]


In [30]:
respuesta[0]

matrix([[1.]])

In [31]:
np.linalg.solve(datos, resultados)

matrix([[1. ],
        [1.2],
        [3.8]])