<img src="../../files/logo.png" width=200>

# Arreglos Multidimensaionales

## Arreglos vs Listas

In [4]:
# necesito importar la libreria numérica
import numpy as np

Una de las principales ventajas de usar `numpy` es el poder de usar vectorización de funciones aplicadas a un `numpy.array`. Esto implica poder aplicar una función a cada `numpy.array` sin necesidad de expresar un *for loop*, lo cuál hace trabajar con este tipo de funciónes más eficientemente.

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,7])
list1 = [1,2,3]
list2 = [2,3,7]

In [6]:
print(f"La suma de los arreglos es: {arr1 + arr2 }")
print(f"La suma de las listas es: {list1+list2 }")

La suma de los arreglos es: [ 3  5 10]
La suma de las listas es: [1, 2, 3, 2, 3, 7]


In [7]:
print(f"La suma de los arreglos es: {arr1 - arr2 }")
#print(f"La suma de las listas es: {list1-list2 }")

La suma de los arreglos es: [-1 -1 -4]


In [8]:
print(f"La suma de los arreglos es: {arr1 /arr2 }")
#print(f"La suma de las listas es: {list1/list2 }")

La suma de los arreglos es: [0.5        0.66666667 0.42857143]


In [9]:
print(f"Mi arreglo 1 por 10: {arr1*10 }")
print(f"Mi lista 1 por 10: {list1 *10 }")

Mi arreglo 1 por 10: [10 20 30]
Mi lista 1 por 10: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [14]:
arr2 // 2 

array([1, 1, 3])

In [10]:
print(sum(arr2)) #2+3+7
print(sum(arr2.cumsum())) # 2 + 5 + 12 

12
19


In [12]:
arr1 = np.array([[1,2,3], [4,5,6]])
print("Mi primera matriz: \n", arr1)

Mi primera matriz: 
 [[1 2 3]
 [4 5 6]]


### Propiedas Principales de `ndarray`

In [9]:
arr1.ndim

2

In [10]:
arr1.shape

(2, 3)

In [12]:
np.array( [1, 2] )

array([1, 2])

In [13]:
np.array( [[1, 2], [3, 4]] )

array([[1, 2],
       [3, 4]])

In [14]:
np.array( [[1, 2], [3, 4], [5, 6]] )

array([[1, 2],
       [3, 4],
       [5, 6]])

## Arreglos con dos dimensiones

In [15]:
a1 = np.array([
     [2, 4, 6],
     [3, 5, 1]
])

In [16]:
a1 + 1

array([[3, 5, 7],
       [4, 6, 2]])

In [17]:
# Elevar al cuadrado cada entrada
a1 ** 2

array([[ 4, 16, 36],
       [ 9, 25,  1]])

In [18]:
# Multiplicación entrada a entrada
a1 * a1

array([[ 4, 16, 36],
       [ 9, 25,  1]])

In [19]:
# Comparación entrada a entrada
a1 <= 3

array([[ True, False, False],
       [ True, False,  True]])

### np.arange, np.linspace
Podemos crear rangos de números $[a, b)$ usando la funcion `arange` (análogo a `range` en Python)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [17]:
# A diferencia de range, np.arange nos permite tomar pasos fraccionarios
np.arange(1, 11, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

Usamos la función `linspace` cuando deseamos un arreglo de $n$ elementos entre $a$ y $b$ (inclusivo); $a < b$

In [18]:
a, b = 2, 10
np.linspace(a, b, 20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

<h2 style="color:#d62728">Ejercicio</h2>

In [13]:
import numpy as np